import { SKILLS, STATUSES, GENDERS, MODES } from './constants.js';
import { eligible, assignment } from './players.js';
import { waitingMinutes } from './matchmaking.js';
import { winPercentage } from './stats.js';
import { playerFees, financeSummary } from './finance.js';
import { escape, name, skill, button, options, field, select, number, empty, money, time } from './ui.js';
const title = (eyebrow, heading, actions = '') => `<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${heading}</h1></div><div class="actions">${actions}</div></div>`;
const metric = (value, label) => `<div class="metric"><strong>${value}</strong><span>${label}</span></div>`;
export function matchCard(s, m, type, index = 0) {
  const controls = type === 'playing' ? button('Finish match', 'finish', m.id, 'primary') : type === 'history' ? button('Correct result / players', 'edit-history', m.id) + button('Delete', 'delete-history', m.id, 'quiet danger') : button('Start match', 'start', m.id, 'primary') + button('Edit teams', 'edit-match', m.id) + button('↑', 'up', m.id, 'icon-button', index === 0) + button('↓', 'down', m.id, 'icon-button', index === s.queue.length - 1) + button('Remove', 'remove-match', m.id, 'quiet');
  const court = m.courtId ? s.courts.find(c => c.id === m.courtId) : null;
  return `<article class="match-card ${type === 'playing' ? 'playing-card' : ''}"><div class="match-meta"><span>${type === 'playing' ? '<i class="live-dot"></i> IN PLAY' : type === 'history' ? 'COMPLETED' : `MATCH ${String(index + 1).padStart(2, '0')}`}</span><span>${type === 'playing' ? `${court ? `${escape(court.name)} · ` : ''}Started ${time(m.startedAt)}` : type === 'history' ? time(m.completedAt) : index === 0 ? 'READY WHEN YOU ARE' : 'RESERVED'}</span></div><div class="teams">${m.teams.map((t, side) => `${side ? '<span class="versus">VS</span>' : ''}<div class="team ${m.winner === side ? 'winner' : ''}">${t.map(id => `<span>${name(s, id)}</span>`).join('')}<small>${m.winner === side ? 'WINNERS' : `TEAM ${side + 1}`}</small></div>`).join('')}</div><div class="match-actions">${controls}</div></article>`;
}

export function courtsView(s) {
  const activeByCourt = new Map(s.activeMatches.filter(m => m.courtId).map(m => [m.courtId, m]));
  const freeCount = s.courts.filter(c => !activeByCourt.has(c.id)).length;
  const cards = s.courts.map(c => {
    const match = activeByCourt.get(c.id);
    return `<section class="panel"><div class="section-title"><h2>${escape(c.name)}</h2><span>${match ? 'IN PLAY' : 'AVAILABLE'}</span></div>${match ? matchCard(s, match, 'playing') : empty('Court ready', s.queue.length ? 'Start the next queued match on this court.' : 'Queue a match first.', s.queue.length ? button('Start next match', 'start-next-on-court', c.id, 'primary') : '')}${match ? '' : `<div class="actions">${button('Remove court', 'remove-court', c.id, 'quiet danger')}</div>`}</section>`;
  }).join('');
  return title('COURT CONTROL', 'Courts', button('+ Add Court', 'add-court', '', 'primary')) +
    `<div class="metrics">${metric(s.courts.length, 'Courts')}${metric(s.activeMatches.length, 'Matches playing')}${metric(freeCount, 'Courts available')}${metric(s.queue.length, 'Matches queued')}</div>` +
    (s.courts.length ? `<div class="queue-grid">${cards}</div>` : empty('No courts yet', 'Add the courts you are using for this session.', button('+ Add Court', 'add-court', '', 'primary')));
}

export function queueView(s, filters) {
  const available = eligible(s);
  return title('THE SESSION / LIVE QUEUE', 'Let’s play.', button('+ Manual match', 'manual') + button('Generate queue', 'generate', '', 'primary')) +
    `<div class="metrics">${metric(available.length, 'Ready to play')}${metric(s.activeMatches.length, 'Matches playing')}${metric(s.queue.length, 'Matches queued')}${metric(s.completedMatches.length, 'Matches finished')}</div><div class="queue-toolbar">${field('Matchmaking', `<select id="mode">${options(MODES, filters.mode)}</select>`)}<p>Fewer games. Longer waits. Fairer matches.</p></div><div class="queue-grid"><section><div class="section-title"><h2><i class="live-dot"></i> Now playing</h2><span>${s.activeMatches.length}</span></div>${s.activeMatches.length ? s.activeMatches.map(m => matchCard(s, m, 'playing')).join('') : empty('Ready for the first rally', 'Start a queued match to bring it here.')}</section><section><div class="section-title"><h2>Up next</h2><span>01</span></div>${s.queue.length ? matchCard(s, s.queue[0], 'queued', 0) : empty('Build the next matchup', s.players.length ? 'Activate at least four players, then generate a queue or choose teams manually.' : 'Add your players to start the session.', !s.players.length ? button('Add players', 'go-players', '', 'primary') : '')}</section></div><section class="remaining"><div class="section-title"><h2>Queue</h2><span>${Math.max(0, s.queue.length - 1)} waiting matches</span></div><div class="queue-grid">${s.queue.slice(1).map((m, i) => matchCard(s, m, 'queued', i + 1)).join('') || '<p class="muted">Additional generated matches will appear here.</p>'}</div></section><details><summary>Available players · ${available.length}</summary><div class="chips">${available.map(p => `<span class="chip">${escape(p.name)} <small>${p.gamesPlayed} games · ${Math.floor(waitingMinutes(p))}m wait</small></span>`).join('') || '<p>No unassigned active players.</p>'}</div></details><details><summary>Standby & checked out · ${s.players.filter(p => p.status !== 'Active').length}</summary><div class="chips">${s.players.filter(p => p.status !== 'Active').map(p => `<span class="chip">${escape(p.name)} <small>${p.status}</small>${button('Activate', 'activate', p.id, 'quiet')}</span>`).join('') || '<p>Everyone is active.</p>'}</div></details><details><summary>Recently completed · ${s.completedMatches.length}</summary>${s.completedMatches.slice(-3).reverse().map(m => matchCard(s, m, 'history')).join('') || '<p>Finished matches will appear here.</p>'}</details>`;
}
export function playersView(s, f) {
  const players = s.players.filter(p => p.name.toLowerCase().includes(f.search.toLowerCase()) && (!f.status || p.status === f.status) && (!f.gender || p.gender === f.gender));
  players.sort((a, b) => f.playerSort === 'games' ? a.gamesPlayed - b.gamesPlayed || a.name.localeCompare(b.name) : f.playerSort === 'skill' ? b.skillLevel - a.skillLevel : a.name.localeCompare(b.name));
  return title('THE ROSTER', 'Players', button('Bulk add', 'bulk') + button('+ Add player', 'add-player', '', 'primary')) + `<div class="filter-bar">${field('Search players', `<input id="search" type="search" placeholder="Search by name…" value="${escape(f.search)}">`)}${field('Status', `<select id="status-filter">${options([['', 'All statuses'], ...STATUSES], f.status)}</select>`)}${field('Gender', `<select id="gender-filter">${options([['', 'All genders'], ...GENDERS], f.gender)}</select>`)}${field('Sort by', `<select id="player-sort">${options([['name', 'Name'], ['games', 'Fewest games'], ['skill', 'Skill level']], f.playerSort)}</select>`)}</div><p class="muted">${players.length} of ${s.players.length} players · ${eligible(s).length} ready to play</p><div class="player-grid">${players.map(p => {
    const m = assignment(s, p.id), playing = s.activeMatches.some(m => m.teams.flat().includes(p.id));
    return `<article class="player-card"><div class="player-top"><span class="avatar">${escape(p.name.slice(0, 1).toUpperCase())}</span><div><h2>${escape(p.name)}</h2><p>${skill(p)} · ${p.gender}</p></div>${button('Edit', 'edit-player', p.id, 'quiet')}</div><div class="player-data"><span class="badge ${p.status === 'Active' ? 'active' : ''}">${m ? playing ? 'Playing' : 'Queued' : p.status}</span><span>${p.gamesPlayed} games</span><span>${p.paid ? 'Paid' : 'Pending'}</span></div><div class="player-controls"><label class="sr-only" for="status-${p.id}">Status for ${escape(p.name)}</label><select id="status-${p.id}" data-status="${p.id}" ${m ? 'disabled title="Finish or remove their match first"' : ''}>${options(STATUSES, p.status)}</select>${button('Delete', 'delete-player', p.id, 'quiet danger')}</div></article>`;
  }).join('')}</div>${!players.length ? empty(s.players.length ? 'No matching players' : 'Your session starts here', s.players.length ? 'Try a different search or filter.' : 'Add player names, skill levels and genders. Everyone starts active.') : ''}`;
}
export function statsView(s, f) {
  const players = [...s.players].sort((a, b) => f.statsSort === 'name' ? a.name.localeCompare(b.name) : f.statsSort === 'percentage' ? winPercentage(b) - winPercentage(a) : b[f.statsSort] - a[f.statsSort]);
  return title('EVERY RALLY COUNTS', 'Session stats', button('Export stats CSV', 'stats-csv') + button('Export matches CSV', 'matches-csv')) + `<div class="metrics">${metric(s.completedMatches.length, 'Completed matches')}${metric(s.players.reduce((n, p) => n + p.gamesPlayed, 0), 'Player-games')}${metric(s.players.length, 'Session players')}</div><div class="filter-bar">${field('Sort by', `<select id="stats-sort">${options([['wins', 'Most wins'], ['gamesPlayed', 'Most games'], ['percentage', 'Win percentage'], ['name', 'Name']], f.statsSort)}</select>`)}</div><div class="table-wrap"><table><thead><tr><th>Player</th><th>Skill level</th><th>Games</th><th>Wins</th><th>Losses</th><th>Win %</th></tr></thead><tbody>${players.map(p => `<tr><th scope="row">${escape(p.name)}</th><td>${skill(p)}</td><td>${p.gamesPlayed}</td><td>${p.wins}</td><td>${p.losses}</td><td>${winPercentage(p)}%</td></tr>`).join('') || '<tr><td colspan="6">Add players to track your session.</td></tr>'}</tbody></table></div><div class="section-title"><h2>Match history</h2><span>${s.completedMatches.length} completed</span></div><p class="muted">Corrections rebuild all player statistics from this history.</p><div class="queue-grid">${[...s.completedMatches].reverse().map(m => matchCard(s, m, 'history')).join('') || '<p class="muted">No completed matches yet.</p>'}</div>`;
}
export function financeView(s) {
  const f = s.finance, sum = financeSummary(s), fmt = cents => money(cents, f.currency);
  return title('KEEP IT SQUARE', 'Finance') + `<div class="metrics">${metric(fmt(sum.cost), 'Session cost')}${metric(fmt(sum.collected), 'Marked paid · current fees')}${metric(fmt(sum.remaining), 'Fees remaining')}${metric(`${sum.paid} / ${s.players.length}`, 'Players paid')}</div><div class="queue-grid"><section class="panel"><h2>Session costs & player fees</h2><form id="finance-form"><div class="form-grid">${field('Session / venue cost', number('sessionCost', f.sessionCost))}${field('Shuttlecock cost each', number('shuttleCost', f.shuttleCost))}${field('Shuttlecocks used', number('shuttleCount', f.shuttleCount, '1', 10000))}${field('Other expenses', number('otherCost', f.otherCost))}${field('Currency', select('currency', ['PHP', 'SGD', 'USD'], f.currency))}${field('Fee rule', select('feeMode', [['equal', 'Equal split'], ['flat', 'Flat fee'], ['per-game', 'Per game'], ['combined', 'Flat + per game']], f.feeMode))}${field('Flat fee per player', number('flatFee', f.flatFee))}${field('Per-game contribution', number('perGame', f.perGame))}</div><button class="primary" type="submit">Save calculations</button></form><p class="muted">Equal split includes the entire roster, including standby and checked-out players. Flat and per-game amounts apply only to their selected fee rule.</p></section><section class="panel"><div class="section-title"><h2>Payment tracker</h2><span>${s.players.length - sum.paid} pending</span></div><div class="actions">${button('Mark all paid', 'all-paid')}${button('Clear all payments', 'clear-paid', '', 'quiet')}</div><p class="muted">Paid is a session flag, separate from checkout. Totals use current calculated fees; changing fees or game counts changes these totals. This is not a payment ledger.</p><div class="payments">${playerFees(s).map(({ player: p, cents }) => `<div class="payment"><div><strong>${escape(p.name)}</strong><small>${p.gamesPlayed} games · ${fmt(cents)}</small></div>${button(p.paid ? 'Paid ✓ · Clear' : 'Mark paid', 'toggle-paid', p.id, p.paid ? 'paid' : '')}</div>`).join('') || '<p>Add players to track payments.</p>'}</div></section></div>`;
}
export function settingsView(s) {
  const labels = { games: 'Fewer games priority', waiting: 'Waiting time priority', arrival: 'Recent arrival penalty', skill: 'Team skill balance', partner: 'Repeat partner penalty', opponent: 'Repeat opponent penalty' };
  return title('SESSION UTILITIES', 'Settings') + `<div class="queue-grid"><section class="panel"><h2>Matchmaking preferences</h2><p class="muted">Higher values give a factor more influence. Changes apply to newly generated matches.</p><form id="settings-form"><div class="form-grid">${Object.entries(s.settings.weights).filter(([k]) => k in labels).map(([k, v]) => field(labels[k], number(k, v, '1', 1000))).join('')}${field('Appearance', select('theme', ['dark', 'light'], s.settings.theme))}</div><button class="primary" type="submit">Save preferences</button></form></section><section class="panel"><h2>Session & backups</h2><p>Started ${escape(new Date(s.session.startedAt).toLocaleString())}</p><p class="muted">Saved in this browser on this device. Export a backup to keep a separate copy or continue on another device.</p><div class="stack">${button('Export full session JSON', 'export', '', 'primary')}<label class="file-button">Import session JSON<input id="import-file" type="file" accept="application/json,.json"></label>${button('Install app', 'install')}</div><hr><h3>Start fresh</h3><p class="muted">New session keeps player profiles and moves them to standby for check-in. Matches, statistics, payments and costs are cleared.</p>${button('Start new session', 'new-session')}<hr><h3>Clear roster</h3><p class="muted">Permanently remove all players and session data from this browser.</p>${button('Clear all players', 'clear-roster', '', 'danger')}<hr><h3>Cloud backup</h3><p class="muted">Cloud accounts are not connected in this local-first version. Use a JSON backup to transfer the full session.</p></section></div>`;
}
